# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "96b0459626063b1c4f0686b444f76bd9"
application_url = "https://editorial-meeting-list-riders.trycloudflare.com"
embedded = true
name = "redeemer"
handle = "redeemer-1"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "customers/create" ]
  uri = "/webhooks/customers"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_products"

[auth]
redirect_urls = [
  "https://editorial-meeting-list-riders.trycloudflare.com/auth/callback",
  "https://editorial-meeting-list-riders.trycloudflare.com/auth/shopify/callback",
  "https://editorial-meeting-list-riders.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
