# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "96b0459626063b1c4f0686b444f76bd9"
application_url = "https://innovations-twice-washing-reel.trycloudflare.com"
embedded = true
name = "redeemer"
handle = "redeemer-1"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://innovations-twice-washing-reel.trycloudflare.com/auth/callback",
  "https://innovations-twice-washing-reel.trycloudflare.com/auth/shopify/callback",
  "https://innovations-twice-washing-reel.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
