# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "96b0459626063b1c4f0686b444f76bd9"
name = "redeemer"
handle = "redeemer-1"
application_url = "https://continuity-organisations-lu-richardson.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "customers/create" ]
  uri = "/webhooks/customers"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_discounts,write_orders,write_products,write_app_proxy,write_publications,unauthenticated_read_content,read_themes"

[auth]
redirect_urls = [
  "https://continuity-organisations-lu-richardson.trycloudflare.com/auth/callback",
  "https://continuity-organisations-lu-richardson.trycloudflare.com/auth/shopify/callback",
  "https://continuity-organisations-lu-richardson.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[app_proxy]
url = "https://continuity-organisations-lu-richardson.trycloudflare.com"
subpath = "my-proxy"
prefix = "apps"
